profile_img: "assets/img/vishal s photo.jpg"
icon_img: assets/img/icon.webp

name: "Vishal Sonth"
job: "AI Strategist | LLM & Prompt Engineering Expert"

phone_number: "+39 328 631 9162"
address: "Naples, Italy, 80139"
email: "vishu.sonth@gmail.com"

linkedin_username: ""
github_username: "VishalSonth"
website: "https://VishalSonth.github.io"

baseurl: ""
url: "https://VishalSonth.github.io"
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
